# Change name to docker-compose.yml

services:
  postgres:
    image: postgres:17-alpine
    ports:
      # yourport:5432
      - 5432:5432
    volumes:
      # Change yourproject to your project name.
      - ~/apps/postgres_yourproject:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=...
      - POSTGRES_USER=...
      - POSTGRES_DB=...
